### ISSUE TITLE
How to clear the validation errors after a dirty state ?

### ISSUE THREAD

**Issue by juanchavezlive** [rfink/angular-vin#1]
Hi @rfink. First of all congratulations for the nice directive.

I have a doubt, and i kindly ask for your help.

How can i clear any error when the directive has no content?

The scenario is the next:
1.- The user entry an invalid value in the textbox, 
2.- The user clear the data.
3.- The form still has error because the directive is expecting a valid VIN, but the field is optional.

**Comment by rfink** [comment]
Thanks for bringing this to my attention.  I'll check into it as soon as I am able.

**Comment by juanchavezlive** [comment]
Thank you very much @rfink. This is the only bug i have found, apart from that i think your directive is great and very easy to use :)

**Comment by rfink** [comment]
My apologies, I haven't gotten to this yet.  I still plan on getting to this error, but my new gig has a release coming up and I've been slammed :P

**Comment by juanchavezlive** [comment]
I would really appreciate your help my friend when you have time. The directive is so flexible and this is the only error i had found

**Comment by rfink** [comment]
Juan, would it work for you if I remove the empty check altogether and let that be handle by "required" or "ng-required"?

**Comment by juanchavezlive** [comment]
Hi @rfink.... Yes it will work for me :)

**Comment by rfink** [comment]
This is done.  The version has been bumped to 0.1.0, and some documentation on building and testing has been added.  Thanks for the feedback.

**Comment by juanchavezlive** [comment]
This is Great !! Thank you very much @rfink  for the support. I will test it and let you know the results :)
