### ISSUE TITLE
Small problem With your bower.json file

### ISSUE THREAD

**Issue by rhett-raleigh** [rfink/angular-vin#2]
In your bower.json file: <code>"main": "./dist/angular-vin.js",</code> this line should read <code>"main": "./dist/assets/angular-vin.js",</code> to reflect your file organization. This is essential so bower can include your project as a dependency for other projects.

**Comment by rfink** [comment]
Well, that is an oversight.  Thanks for reporting this.  Fixed in release 0.2.0.
